# Generated by Django 3.2 on 2021-04-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Sourse url')),
                ('title', models.CharField(max_length=50, verbose_name='Node title')),
                ('description', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('pathway', 'Pathway'), ('course', 'Course'), ('video', 'Video'), ('article', 'Article'), ('generic', 'Generic')], default='generic', max_length=7, verbose_name='Sourse type')),
                ('children', models.ManyToManyField(blank=True, null=True, related_name='_core_node_children_+', to='core.Node')),
            ],
        ),
    ]
