# Generated by Django 3.2 on 2021-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='children',
            field=models.ManyToManyField(blank=True, null=True, to='core.Node'),
        ),
    ]
