# Generated by Django 3.2 on 2021-04-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(blank=True, default='811c0f00-9958-4563-a361-4415c6d82f66', max_length=64),
        ),
    ]
