name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: staging07.raccoongang.com
        username: raccoon
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 28177
        script: |
          cd learning_path
          git pull
          docker-compose up --build -d